### ISSUE TITLE
Another small item... Quotes.

### ISSUE THREAD

**Issue by jhollist** [sckott/rforcats#12]
Single or double quotes? 

They are both used throughout.  Might be a source of confusion for many cats.

Any opinions on one way or the other?

I can make the changes and submit a PR, but want to do it the right way!

**Comment by sckott** [comment]
@jhollist Agreed, confusing.

**Comment by sckott** [comment]
`?Quotes` shows that 

> They can be used interchangeably but double quotes are preferred

So let's go with double. Can you PR?

**Comment by jhollist** [comment]
Yup... PR coming soon.
