### ISSUE TITLE
consider the devel version of knitr and collapse=TRUE

### ISSUE THREAD

**Issue by yihui** [sckott/rforcats#8]
The new chunk option `collapse=TRUE` might be better for index.Rmd, since your examples are normally short; the input and output blocks can be merged into a single block. That is what adv-r does.

**Comment by sckott** [comment]
Thanks @yihui for the recommendation. Do you think that collapsing input and output into the same block is better for readers? Or simply to take up less space?

**Comment by yihui** [comment]
I think collapsing the input and output improves the readability when the input and output pieces are short. It is a little disturbing to my eyes when each short piece occupies a separate block.

**Comment by sckott** [comment]
Okay, that makes sense.

**Comment by yihui** [comment]
Or you can actually `opts_chunk$set(collapse = TRUE)` :)

**Comment by sckott** [comment]
Right, didn't want `collapse=TRUE` for all chunks, but I can override on individual chunks i guess

**Comment by yihui** [comment]
Exactly. If you find yourself using a chunk option repeatedly on most chunks, it is time to set it as a global option, and only override it in the rest of chunks (much fewer).
