### ISSUE TITLE
R is clearly for dogs

### ISSUE THREAD

**Issue by baptiste** [sckott/rforcats#9]
who ever heard of a cat growling Rrr?

![rrr](https://cloud.githubusercontent.com/assets/18970/3229588/6a5519c8-f097-11e3-9938-20e21d4a0fca.png)

**Comment by baptiste** [comment]
[I see you're aware of the issue](http://rforcats.net/#doge).

**Comment by sckott** [comment]
@baptiste  You're right that cat's don't make that noise. If it wasn't for [jsforcats.com](http://jsforcats.com/) :cat2:  I probably would have gone with dogs :dog2:
